import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import type { SimulatorManager } from "../simulatorManager.js";
import type { InspectorManager } from "../inspector/index.js";
import type { AutomationManager } from "../automation/automationManager.js";
export declare const allTools: readonly [{
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}, {
    name: string;
    description: string;
    input_schema: any;
    output_schema: any;
}];
export type ToolDefinitions = (typeof allTools)[number];
export declare function callTool(name: string, args: unknown, managers: {
    simulator: SimulatorManager;
    inspector: InspectorManager;
    automation: AutomationManager;
}): Promise<CallToolResult>;
//# sourceMappingURL=index.d.ts.map